name: Python Backend CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v test

      - name: Validate OpenAPI Spec
        run: |
          pip install openapi-spec-validator
          python -c "from openapi_spec_validator import validate_spec; import yaml; spec=yaml.safe_load(open('docs/api_spec.yaml')); validate_spec(spec)"

      - name: Regenerate collections
        run: python scripts/update_collections.py

      - name: Check for uncommitted changes
        run: |
          git diff --exit-code || (echo "❌ Collections or docs are outdated. Run 'python scripts/update_collections.py' and commit changes." && exit 1)
